version: '3'
services:
    workspace:
        tty: true
        build: .
        image: nishiakwa/nishikawa_grad_mayekawa
        container_name: 'nishikawa_grad_mayekawa'
        deploy:
            resources:
                reservations:
                    devices:
                    - driver: nvidia
                      count: all
                      capabilities: [gpu]
        volumes:
            - ../mount:/root/workspace
        #ports:
        # - 58080: 8080
